---
- name: install some useful packages 
  yum: name={{ item }} state=latest
  with_items:
  - git
  - supervisor
  - libselinux-python
  - python-pip
  - python-jinja2
  - python-devel
  - unzip

- name: pip ansible install
  action: command pip install ansible
  sudo: yes

- name: download AWX setup
  get_url: url=http://www.ansibleworks.com/releases/awx/setup/awx-setup-{{awx_version}}.tar.gz
           dest=/opt/ force=yes

- name: extract AWX
  command: chdir=/opt/ creates=/opt/awx-setup-{{awx_version}} tar zxvf awx-setup-{{awx_version}}.tar.gz

- name: run the AWX installer
  command: chdir=/opt/awx-setup-{{awx_version}} creates=/etc/awx/settings.py ./setup.sh

- name: set up private keys for demo boxes
  copy: src=id_rsa dest={{keydir}}/id_rsa mode=0600

- name: move example playbook
  copy: src=lamp_haproxy.zip dest={{playbookdir}}

- name: extract example playbook
  command: chdir={{playbookdir}} creates={{playbookdir}}/lamp_haproxy unzip lamp_haproxy.zip

- name: link playbookdir to home directory
  shell: ln -s {{playbookdir}} /home/vagrant/projects

- name: create etc ansible directory
  action: file dest={{configdir}} state=directory

- name: populate etc ansible hosts
  copy: src=hosts dest={{hostfile}}

- name: populate etc ansible config
  copy: src=ansible.cfg dest=/{{configdir}}

- name: fix permissions
  shell: sudo chown -R vagrant.vagrant /home/vagrant