---
- name: install some useful packages 
  yum: name={{ item }} state=latest
  with_items:
  - git
  - supervisord
  - libselinux-python
  - python-pip
  when: ansible_os_family == "RedHat"

- name: debian pip ansible install
  action: command pip install ansible
  sudo: yes
  when: ansible_os_family == "RedHat"

- name: install some useful packages 
  apt: name={{ item }} state=latest
  with_items:
  - git
  - python-pip
  - python-jinja2
  - supervisor
  when: ansible_os_family == "Debian"

- name: debian pip ansible install
  action: command pip install ansible
  sudo: yes
  when: ansible_os_family == "Debian"

- name: download AWX setup
  get_url: url=http://www.ansibleworks.com/releases/awx/setup/awx-setup-{{awx_version}}.tar.gz
           dest=/opt/ force=yes

- name: extract AWX
  command: chdir=/opt/ creates=/opt/awx-setup-{{awx_version}} tar zxvf awx-setup-{{awx_version}}.tar.gz

- name: run the AWX installer
  command: chdir=/opt/awx-setup-{{awx_version}} creates=/etc/awx/settings.py ./setup.sh