---
- name: install some useful packages 
  yum: name={{ item }} state=latest
  with_items:
  - git
  - supervisor
  - libselinux-python
  - python-pip
  - python-jinja2
  - python-devel
  when: ansible_os_family == "RedHat"

- name: install some useful packages 
  apt: name={{ item }} state=latest
  with_items:
  - git
  - python-pip
  - python-jinja2
  - supervisor
  - libselinux-python
  when: ansible_os_family == "Debian"

- name: pip ansible install
  action: command pip install ansible
  sudo: yes

- name: download AWX setup
  get_url: url=http://www.ansibleworks.com/releases/awx/setup/awx-setup-{{awx_version}}.tar.gz
           dest=/opt/ force=yes

- name: extract AWX
  command: chdir=/opt/ creates=/opt/awx-setup-{{awx_version}} tar zxvf awx-setup-{{awx_version}}.tar.gz

- name: run the AWX installer
  command: chdir=/opt/awx-setup-{{awx_version}} creates=/etc/awx/settings.py ./setup.sh

- name: set up private keys for demo boxes
  copy: src=id_rsa dest={{keydir}}/id_rsa mode=0600

- name: Clone git repo for example playbooks
  action: file dest={{gitdir}} state=directory
  action: git repo={{gitrepo}} dest={{gitdir}}

- name: create etc ansible directory
  action: file dest={{configdir}} state=directory

- name: populate etc ansible directory
  action: copy src=ansible.cfg dest=/{{configdir}}
  action: copy src=hosts dest={{hostfile}}

- name: fix permissions
  shell: sudo chown -R vagrant.vagrant /home/vagrant

