---
- name: install some useful packages 
  yum: name={{ item }} state=latest
  with_items:
  - git
  - supervisor
  - python-pip
  - python-jinja2
  - python-devel
  - unzip

- name: pip ansible install
  action: command pip install ansible
  sudo: yes

- name: download AWX setup
  get_url: url=http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{tower_version}}.tar.gz
           dest=/opt/ force=yes

- name: extract AWX
  command: chdir=/opt/ creates=/opt/ansible-tower-setup-{{tower_version}} tar zxvf ansible-tower-setup-{{tower_version}}.tar.gz

- name: run the AWX installer
  command: chdir=/opt/ansible-tower-setup-{{tower_version}} creates=/etc/awx/settings.py ./setup.sh

- name: set up private keys for demo boxes
  copy: src=id_rsa dest={{keydir}}/id_rsa mode=0600

- name: create etc ansible directory
  action: file dest={{configdir}} state=directory

- name: populate etc ansible hosts
  copy: src=hosts dest={{hostfile}}

- name: populate etc ansible config
  copy: src=ansible.cfg dest=/{{configdir}}

- name: git clone playbook examples to awx projects folder
  command: rsync -a {{playbookdir}}/ /var/lib/awx/projects/

- name: fix AWX permissions
  shell: sudo chown -R awx.awx /var/lib/awx