---
- name: install some useful packages 
  yum: name={{ item }} state=latest
  with_items:
  - git
  - supervisor
  - python-pip
  - python-jinja2
  - python-devel
  - unzip
  - python-crypto2.6.x86_64

- name: EPEL testing install of ansible
  shell: yum install ansible --enablerepo epel-testing

- name: download Tower setup
  get_url: url=http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{tower_version}}.tar.gz
    dest=/opt/ force=yes

- name: extract Tower
  command: chdir=/opt/ creates=/opt/ansible-tower-setup-{{tower_version}} tar zxvf ansible-tower-setup-{{tower_version}}.tar.gz

- name: run the Tower installer
  command: chdir=/opt/ansible-tower-setup-{{tower_version}} creates=/etc/awx/settings.py ./setup.sh

- name: set up private keys for demo boxes
  copy: src=id_rsa dest={{keydir}}/id_rsa mode=0600 owner=vagrant group=vagrant

- name: create etc ansible directory
  action: file dest={{configdir}} state=directory

- name: populate etc ansible hosts
  copy: src=hosts dest={{hostfile}}

- name: populate etc ansible config
  copy: src=ansible.cfg dest=/{{configdir}}

- name: Vagrant user demo playbook directory
  file: path=/home/vagrant/playbooks owner=vagrant group=vagrant mode=755 state=directory

- name: put lamp_haproxy example in user playbook dir
  git: repo={{ playbookrepo }} dest={{ userplaybookdir }} accept_hostkey=yes

- name: fix vagrant home permissions
  shell: sudo chown -R vagrant.vagrant /home/vagrant

- name: git clone tower cli
  git: repo={{ clirepository }} dest={{ clibuilddir }}

- name: install tower cli
  shell: cd /tmp/awx-cli; make install

#NOTE: Next two tasks are dirty fix until I rework the ansible install process above for CentOS

# - name: first perl fix for mpx_powm_sec warning
#   shell: perl -p -i -e "s/^(if _fastmath is not None .*:)/#\1/" /usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Util/number.py

# - name: second perl fix for mpx_powm_sec warning
#   shell: perl -p -i -e "s/^(\s*_warn.*Not using mpz_powm_sec.*)/#\1/" /usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Util/number.py

